//
//  URLs.swift
//  Baccvs iOS
//
//  Created by pm on 16/02/2023.

import Foundation
let baseURL                 = "https://web-production-10c7.up.railway.app/"
let checkReferralCode       = "\(baseURL)check_referral_code"
let signupDev               = "\(baseURL)user_sign_up"
let loginDev                = "\(baseURL)login"
let createEventDev          = "\(baseURL)event_create"
let getEventDev             = "\(baseURL)event_get"
let MyEventsDev             = "\(baseURL)get_my_event"
let reportEventsDev         = "\(baseURL)report_post"
let createGroupDev          = "\(baseURL)create_group"
let myGroupDev              = "\(baseURL)get_my_group"
let profileImageDev         = "\(baseURL)profile_image"
let allGroupDev             = "\(baseURL)all_groups"
let getAllEventsDev         = "\(baseURL)get_all_feed"
let profileIimageDev        = "\(baseURL)profile_image"
let checkProfileDev         = "\(baseURL)check_profile"
let groupLikeDev            = "\(baseURL)get_group_like"
let groupsLikesDev          = "\(baseURL)group_like"
let groupsLikesYouDev       = "\(baseURL)get_group_you_like"
let peopleLikeYouDev        = "\(baseURL)get_people_like_you"
let peopleLikeDev           = "\(baseURL)get_people_i_like"
let followingUserDev        = "\(baseURL)check_following"
let followerUserDev         = "\(baseURL)follower_user"
let yamatetaDev             = "\(baseURL)yamateta_people"
let allUserHashmiDev        = "\(baseURL)get_all_user_for_hashmi"
let blockUserDev            = "\(baseURL)block_user"
let allBlockUserDev         = "\(baseURL)get_all_block_user"
let unBlockUserDev          = "\(baseURL)unblock_user"
let updatePasswordDev       = "\(baseURL)update_password"
let deActivateDev           = "\(baseURL)deactivate_user"
let createReferralDev       = "\(baseURL)create_referral"
let getAllUsersUrl          = "\(baseURL)get_all_user"
let getInvitationDev        = "\(baseURL)get_invitation_event"
let getSendInvitationDev    = "\(baseURL)sent_invetation"
let sendOtpDev              = "\(baseURL)send-otp"
let eventAcceptDev          = "\(baseURL)event_accepted"
let eventRefuseDev          = "\(baseURL)invitation_refuse_event"
let isPublicDev             = "\(baseURL)is_public"
let postsForUsersDev        = "\(baseURL)posts_for_users_home"
let userIdDev               = "\(baseURL)get_user_id"
let addStory                = "\(baseURL)add_user_story"
let userlistOfLikesDev      = "\(baseURL)get_group_like"
let feedBackDev             = "\(baseURL)feed_back"
let allReferralCodeDev      = "\(baseURL)get_all_referral_code"
let groupLikeURL            = "\(baseURL)group_like"
let isUnlimitedURL          = "\(baseURL)is_unlimited"
let getEventById            = "\(baseURL)event_by_id"
let removeFollowerDev       = "\(baseURL)remove_follower"
let followingDev            = "\(baseURL)following_user"
let blockUserURL            = "\(baseURL)block_user"
let personEventURL          = "\(baseURL)get_person_event"
let createPostGroup         = "\(baseURL)create_post_group"
let deleteEventDev          = "\(baseURL)delete_event"
let addUserStoryURL         = "\(baseURL)add_user_story"
let updateEventDev          = "\(baseURL)update_event"
let deleteEventVideoURL     = "\(baseURL)delete_event_video"
let deleteEventUserUrl      = "\(baseURL)delete_event_user"
let addNewVideoEventUrl     = "\(baseURL)add_new_video"
let updateThumnailEventUrl  = "\(baseURL)update_thumnail"
let updateUserEvent         = "\(baseURL)update_user_event"
let updateProfileDev        = "\(baseURL)update_profile"
let notificationDev         = "\(baseURL)get_notifications"
let  unfollowDev            = "\(baseURL)unfollow"
let  getGroupPostsDev       = "\(baseURL)get_group_posts"
let  updateGroupDev         = "\(baseURL)update_group"
let  deleteGroupUserDev     = "\(baseURL)delete_group_user"
let isPublicURL             = "\(baseURL)is_public"
let isPrivateURL            = "\(baseURL)is_private"
let deleteGroupURL          = "\(baseURL)delete_group"
let  peopleLikeURL          = "\(baseURL)People_likes"
let  eventLikeURL           = "\(baseURL)event_like"
let  deleteImageURL         = "\(baseURL)delete_image"
let  getGroupPostURL        = "\(baseURL)get_group_posts"
let  deleteGropURL          = "\(baseURL)delete_group_user"
let  updateGropUserURL      = "\(baseURL)update_user_group"
let  getallReportsURL       = "\(baseURL)get_all_report"
let  deleteReportsURL       = "\(baseURL)delete_reported_event"
let  verifyOtpURL           = "\(baseURL)verify_otp"
let  upgradeProfileURL      = "\(baseURL)Upgrade_Profile"
let  deleteAccountURL       = "\(baseURL)delete_account_permanently"



//let baseURL                 = "https://web-production-232c.up.railway.app/"
