//
//  CountryCodeList.swift
//  Baccvs iOS
//
//  Created by pm on 13/04/2023.
//

import Foundation

struct CountryCodeModel : Identifiable{
    var id = UUID()
    let name, flag, code, dialCode: String
}

let dectContry = [
    CountryCodeModel(name:"Afghanistan",flag:"🇦🇫",code:"AF",dialCode:"+93"),
    CountryCodeModel(name:"Åland Islands",flag:"🇦🇽",code:"AX",dialCode:"+358"),
    CountryCodeModel(name:"Albania",flag:"🇦🇱",code:"AL",dialCode:"+355"),
    CountryCodeModel(name:"Algeria",flag:"🇩🇿",code:"DZ",dialCode:"+213"),
    CountryCodeModel(name:"American Samoa",flag:"🇦🇸",code:"AS",dialCode:"+1684"),
    CountryCodeModel(name:"Andorra",flag:"🇦🇩",code:"AD",dialCode:"+376"),
    CountryCodeModel(name:"Angola",flag:"🇦🇴",code:"AO",dialCode:"+244"),
    CountryCodeModel(name:"Anguilla",flag:"🇦🇮",code:"AI",dialCode:"+1264"),
    CountryCodeModel(name:"Antarctica",flag:"🇦🇶",code:"AQ",dialCode:"+672"),
    CountryCodeModel(name:"Antigua andBarbuda",flag:"🇦🇬",code:"AG",dialCode:"+1268"),
    CountryCodeModel(name:"Argentina",flag:"🇦🇷",code:"AR",dialCode:"+54"),
    CountryCodeModel(name:"Armenia",flag:"🇦🇲",code:"AM",dialCode:"+374"),
    CountryCodeModel(name:"Aruba",flag:"🇦🇼",code:"AW",dialCode:"+297"),
    CountryCodeModel(name:"Australia",flag:"🇦🇺",code:"AU",dialCode:"+61"),
    CountryCodeModel(name:"Austria",flag:"🇦🇹",code:"AT",dialCode:"+43"),
    CountryCodeModel(name:"Azerbaijan",flag:"🇦🇿",code:"AZ",dialCode:"+994"),
    CountryCodeModel(name:"Bahamas",flag:"🇧🇸",code:"BS",dialCode:"+1242"),
    CountryCodeModel(name:"Bahrain",flag:"🇧🇭",code:"BH",dialCode:"+973"),
    CountryCodeModel(name:"Bangladesh",flag:"🇧🇩",code:"BD",dialCode:"+880"),
    CountryCodeModel(name:"Barbados",flag:"🇧🇧",code:"BB",dialCode:"+1246"),
    CountryCodeModel(name:"Belarus",flag:"🇧🇾",code:"BY",dialCode:"+375"),
    CountryCodeModel(name:"Belgium",flag:"🇧🇪",code:"BE",dialCode:"+32"),
    CountryCodeModel(name:"Belize",flag:"🇧🇿",code:"BZ",dialCode:"+501"),
    CountryCodeModel(name:"Benin",flag:"🇧🇯",code:"BJ",dialCode:"+229"),
    CountryCodeModel(name:"Bermuda",flag:"🇧🇲",code:"BM",dialCode:"+1441"),
    CountryCodeModel(name:"Bhutan",flag:"🇧🇹",code:"BT",dialCode:"+975"),CountryCodeModel(name:"Bolivia, Plurinational State of bolivia",flag:"🇧🇴",code:"BO",dialCode:"+591"),CountryCodeModel(name:"Bosnia and Herzegovina",flag:"🇧🇦",code:"BA",dialCode:"+387"),
    CountryCodeModel(name:"Botswana",flag:"🇧🇼",code:"BW",dialCode:"+267"),CountryCodeModel(name:"Bouvet Island",flag:"🇧🇻",code:"BV",dialCode:"+47"),
    CountryCodeModel(name:"Brazil",flag:"🇧🇷",code:"BR",dialCode:"+55"),CountryCodeModel(name:"British Indian Ocean Territory",flag:"🇮🇴",code:"IO",dialCode:"+246"),CountryCodeModel(name:"Brunei Darussalam",flag:"🇧🇳",code:"BN",dialCode:"+673"),
    CountryCodeModel(name:"Bulgaria",flag:"🇧🇬",code:"BG",dialCode:"+359"),CountryCodeModel(name:"Burkina Faso",flag:"🇧🇫",code:"BF",dialCode:"+226"),
    CountryCodeModel(name:"Burundi",flag:"🇧🇮",code:"BI",dialCode:"+257"),
    CountryCodeModel(name:"Cambodia",flag:"🇰🇭",code:"KH",dialCode:"+855"),
    CountryCodeModel(name:"Cameroon",flag:"🇨🇲",code:"CM",dialCode:"+237"),
    CountryCodeModel(name:"Canada",flag:"🇨🇦",code:"CA",dialCode:"+1"),CountryCodeModel(name:"Cape Verde",flag:"🇨🇻",code:"CV",dialCode:"+238"),CountryCodeModel(name:"Cayman Islands",flag:"🇰🇾",code:"KY",dialCode:"+345"),CountryCodeModel(name:"Central African Republic",flag:"🇨🇫",code:"CF",dialCode:"+236"),
    CountryCodeModel(name:"Chad",flag:"🇹🇩",code:"TD",dialCode:"+235"),
    CountryCodeModel(name:"Chile",flag:"🇨🇱",code:"CL",dialCode:"+56"),
    CountryCodeModel(name:"China",flag:"🇨🇳",code:"CN",dialCode:"+86"),CountryCodeModel(name:"Christmas Island",flag:"🇨🇽",code:"CX",dialCode:"+61"),CountryCodeModel(name:"Cocos (Keeling) Islands",flag:"🇨🇨",code:"CC",dialCode:"+61"),
    CountryCodeModel(name:"Colombia",flag:"🇨🇴",code:"CO",dialCode:"+57"),
    CountryCodeModel(name:"Comoros",flag:"🇰🇲",code:"KM",dialCode:"+269"),
    CountryCodeModel(name:"Congo",flag:"🇨🇬",code:"CG",dialCode:"+242"),CountryCodeModel(name:"Congo, The Democratic Republic of the Congo",flag:"🇨🇩",code:"CD",dialCode:"+243"),CountryCodeModel(name:"Cook Islands",flag:"🇨🇰",code:"CK",dialCode:"+682"),CountryCodeModel(name:"Costa Rica",flag:"🇨🇷",code:"CR",dialCode:"+506"),CountryCodeModel(name:"Cote d'Ivoire",flag:"🇨🇮",code:"CI",dialCode:"+225"),
    CountryCodeModel(name:"Croatia",flag:"🇭🇷",code:"HR",dialCode:"+385"),
    CountryCodeModel(name:"Cuba",flag:"🇨🇺",code:"CU",dialCode:"+53"),
    CountryCodeModel(name:"Cyprus",flag:"🇨🇾",code:"CY",dialCode:"+357"),CountryCodeModel(name:"Czech Republic",flag:"🇨🇿",code:"CZ",dialCode:"+420"),
    CountryCodeModel(name:"Denmark",flag:"🇩🇰",code:"DK",dialCode:"+45"),
    CountryCodeModel(name:"Djibouti",flag:"🇩🇯",code:"DJ",dialCode:"+253"),
    CountryCodeModel(name:"Dominica",flag:"🇩🇲",code:"DM",dialCode:"+1767"),CountryCodeModel(name:"Dominican Republic",flag:"🇩🇴",code:"DO",dialCode:"+1849"),
    CountryCodeModel(name:"Ecuador",flag:"🇪🇨",code:"EC",dialCode:"+593"),
    CountryCodeModel(name:"Egypt",flag:"🇪🇬",code:"EG",dialCode:"+20"),CountryCodeModel(name:"El Salvador",flag:"🇸🇻",code:"SV",dialCode:"+503"),CountryCodeModel(name:"Equatorial Guinea",flag:"🇬🇶",code:"GQ",dialCode:"+240"),
    CountryCodeModel(name:"Eritrea",flag:"🇪🇷",code:"ER",dialCode:"+291"),
    CountryCodeModel(name:"Estonia",flag:"🇪🇪",code:"EE",dialCode:"+372"),
    CountryCodeModel(name:"Ethiopia",flag:"🇪🇹",code:"ET",dialCode:"+251"),CountryCodeModel(name:"Falkland Islands (Malvinas)",flag:"🇫🇰",code:"FK",dialCode:"+500"),CountryCodeModel(name:"Faroe Islands",flag:"🇫🇴",code:"FO",dialCode:"+298"),
    CountryCodeModel(name:"Fiji",flag:"🇫🇯",code:"FJ",dialCode:"+679"),
    CountryCodeModel(name:"Finland",flag:"🇫🇮",code:"FI",dialCode:"+358"),
    CountryCodeModel(name:"France",flag:"🇫🇷",code:"FR",dialCode:"+33"),CountryCodeModel(name:"French Guiana",flag:"🇬🇫",code:"GF",dialCode:"+594"),CountryCodeModel(name:"French Polynesia",flag:"🇵🇫",code:"PF",dialCode:"+689"),CountryCodeModel(name:"French Southern Territories",flag:"🇹🇫",code:"TF",dialCode:"+262"),
    CountryCodeModel(name:"Gabon",flag:"🇬🇦",code:"GA",dialCode:"+241"),
    CountryCodeModel(name:"Gambia",flag:"🇬🇲",code:"GM",dialCode:"+220"),
    CountryCodeModel(name:"Georgia",flag:"🇬🇪",code:"GE",dialCode:"+995"),
    CountryCodeModel(name:"Germany",flag:"🇩🇪",code:"DE",dialCode:"+49"),
    CountryCodeModel(name:"Ghana",flag:"🇬🇭",code:"GH",dialCode:"+233"),
    CountryCodeModel(name:"Gibraltar",flag:"🇬🇮",code:"GI",dialCode:"+350"),
    CountryCodeModel(name:"Greece",flag:"🇬🇷",code:"GR",dialCode:"+30"),
    CountryCodeModel(name:"Greenland",flag:"🇬🇱",code:"GL",dialCode:"+299"),
    CountryCodeModel(name:"Grenada",flag:"🇬🇩",code:"GD",dialCode:"+1473"),
    CountryCodeModel(name:"Guadeloupe",flag:"🇬🇵",code:"GP",dialCode:"+590"),
    CountryCodeModel(name:"Guam",flag:"🇬🇺",code:"GU",dialCode:"+1671"),
    CountryCodeModel(name:"Guatemala",flag:"🇬🇹",code:"GT",dialCode:"+502"),
    CountryCodeModel(name:"Guernsey",flag:"🇬🇬",code:"GG",dialCode:"+44"),
    CountryCodeModel(name:"Guinea",flag:"🇬🇳",code:"GN",dialCode:"+224"),
    CountryCodeModel(name:"Guinea-Bissau",flag:"🇬🇼",code:"GW",dialCode:"+245"),
    CountryCodeModel(name:"Guyana",flag:"🇬🇾",code:"GY",dialCode:"+592"),
    CountryCodeModel(name:"Haiti",flag:"🇭🇹",code:"HT",dialCode:"+509"),CountryCodeModel(name:"Heard Island and Mcdonald Islands",flag:"🇭🇲",code:"HM",dialCode:"+672"),CountryCodeModel(name:"Holy See (Vatican City State)",flag:"🇻🇦",code:"VA",dialCode:"+379"),
    CountryCodeModel(name:"Honduras",flag:"🇭🇳",code:"HN",dialCode:"+504"),CountryCodeModel(name:"Hong Kong",flag:"🇭🇰",code:"HK",dialCode:"+852"),
    CountryCodeModel(name:"Hungary",flag:"🇭🇺",code:"HU",dialCode:"+36"),
    CountryCodeModel(name:"Iceland",flag:"🇮🇸",code:"IS",dialCode:"+354"),
    CountryCodeModel(name:"India",flag:"🇮🇳",code:"IN",dialCode:"+91"),
    CountryCodeModel(name:"Indonesia",flag:"🇮🇩",code:"ID",dialCode:"+62"),CountryCodeModel(name:"Iran, Islamic Republic of Persian Gulf",flag:"🇮🇷",code:"IR",dialCode:"+98"),CountryCodeModel(name:"Iraq",flag:"🇮🇶",code:"IQ",dialCode:"+964"),
    CountryCodeModel(name:"Ireland",flag:"🇮🇪",code:"IE",dialCode:"+353"),CountryCodeModel(name:"Isle of Man",flag:"🇮🇲",code:"IM",dialCode:"+44"),CountryCodeModel(name:"Israel",flag:"🇮🇱",code:"IL",dialCode:"+972"),
    CountryCodeModel(name:"Italy",flag:"🇮🇹",code:"IT",dialCode:"+39"),
    CountryCodeModel(name:"Jamaica",flag:"🇯🇲",code:"JM",dialCode:"+1876"),
    CountryCodeModel(name:"Japan",flag:"🇯🇵",code:"JP",dialCode:"+81"),
    CountryCodeModel(name:"Jersey",flag:"🇯🇪",code:"JE",dialCode:"+44"),
    CountryCodeModel(name:"Jordan",flag:"🇯🇴",code:"JO",dialCode:"+962"),
    CountryCodeModel(name:"Kazakhstan",flag:"🇰🇿",code:"KZ",dialCode:"+7"),
    CountryCodeModel(name:"Kenya",flag:"🇰🇪",code:"KE",dialCode:"+254"),
    CountryCodeModel(name:"Kiribati",flag:"🇰🇮",code:"KI",dialCode:"+686"),CountryCodeModel(name:"Korea, Democratic People's Republic of Korea",flag:"🇰🇵",code:"KP",dialCode:"+850"),CountryCodeModel(name:"Korea, Republic of South Korea",flag:"🇰🇷",code:"KR",dialCode:"+82"),
    CountryCodeModel(name:"Kosovo",flag:"🇽🇰",code:"XK",dialCode:"+383"),
    CountryCodeModel(name:"Kuwait",flag:"🇰🇼",code:"KW",dialCode:"+965"),
    CountryCodeModel(name:"Kyrgyzstan",flag:"🇰🇬",code:"KG",dialCode:"+996"),
    CountryCodeModel(name:"Laos",flag:"🇱🇦",code:"LA",dialCode:"+856"),
    CountryCodeModel(name:"Latvia",flag:"🇱🇻",code:"LV",dialCode:"+371"),
    CountryCodeModel(name:"Lebanon",flag:"🇱🇧",code:"LB",dialCode:"+961"),
    CountryCodeModel(name:"Lesotho",flag:"🇱🇸",code:"LS",dialCode:"+266"),
    CountryCodeModel(name:"Liberia",flag:"🇱🇷",code:"LR",dialCode:"+231"),CountryCodeModel(name:"Libyan Arab Jamahiriya",flag:"🇱🇾",code:"LY",dialCode:"+218"),
    CountryCodeModel(name:"Liechtenstein",flag:"🇱🇮",code:"LI",dialCode:"+423"),
    CountryCodeModel(name:"Lithuania",flag:"🇱🇹",code:"LT",dialCode:"+370"),
    CountryCodeModel(name:"Luxembourg",flag:"🇱🇺",code:"LU",dialCode:"+352"),
    CountryCodeModel(name:"Macao",flag:"🇲🇴",code:"MO",dialCode:"+853"),
    CountryCodeModel(name:"Macedonia",flag:"🇲🇰",code:"MK",dialCode:"+389"),
    CountryCodeModel(name:"Madagascar",flag:"🇲🇬",code:"MG",dialCode:"+261"),
    CountryCodeModel(name:"Malawi",flag:"🇲🇼",code:"MW",dialCode:"+265"),
    CountryCodeModel(name:"Malaysia",flag:"🇲🇾",code:"MY",dialCode:"+60"),
    CountryCodeModel(name:"Maldives",flag:"🇲🇻",code:"MV",dialCode:"+960"),
    CountryCodeModel(name:"Mali",flag:"🇲🇱",code:"ML",dialCode:"+223"),
    CountryCodeModel(name:"Malta",flag:"🇲🇹",code:"MT",dialCode:"+356"),CountryCodeModel(name:"Marshall Islands",flag:"🇲🇭",code:"MH",dialCode:"+692"),
    CountryCodeModel(name:"Martinique",flag:"🇲🇶",code:"MQ",dialCode:"+596"),
    CountryCodeModel(name:"Mauritania",flag:"🇲🇷",code:"MR",dialCode:"+222"),
    CountryCodeModel(name:"Mauritius",flag:"🇲🇺",code:"MU",dialCode:"+230"),
    CountryCodeModel(name:"Mayotte",flag:"🇾🇹",code:"YT",dialCode:"+262"),
    CountryCodeModel(name:"Mexico",flag:"🇲🇽",code:"MX",dialCode:"+52"),CountryCodeModel(name:"Micronesia, Federated States of Micronesia",flag:"🇫🇲",code:"FM",dialCode:"+691"),
    CountryCodeModel(name:"Moldova",flag:"🇲🇩",code:"MD",dialCode:"+373"),
    CountryCodeModel(name:"Monaco",flag:"🇲🇨",code:"MC",dialCode:"+377"),
    CountryCodeModel(name:"Mongolia",flag:"🇲🇳",code:"MN",dialCode:"+976"),
    CountryCodeModel(name:"Montenegro",flag:"🇲🇪",code:"ME",dialCode:"+382"),
    CountryCodeModel(name:"Montserrat",flag:"🇲🇸",code:"MS",dialCode:"+1664"),
    CountryCodeModel(name:"Morocco",flag:"🇲🇦",code:"MA",dialCode:"+212"),
    CountryCodeModel(name:"Mozambique",flag:"🇲🇿",code:"MZ",dialCode:"+258"),
    CountryCodeModel(name:"Myanmar",flag:"🇲🇲",code:"MM",dialCode:"+95"),
    CountryCodeModel(name:"Namibia",flag:"🇳🇦",code:"NA",dialCode:"+264"),
    CountryCodeModel(name:"Nauru",flag:"🇳🇷",code:"NR",dialCode:"+674"),
    CountryCodeModel(name:"Nepal",flag:"🇳🇵",code:"NP",dialCode:"+977"),
    CountryCodeModel(name:"Netherlands",flag:"🇳🇱",code:"NL",dialCode:"+31"),CountryCodeModel(name:"Netherlands Antilles",flag:"",code:"AN",dialCode:"+599"),CountryCodeModel(name:"New Caledonia",flag:"🇳🇨",code:"NC",dialCode:"+687"),CountryCodeModel(name:"New Zealand",flag:"🇳🇿",code:"NZ",dialCode:"+64"),
    CountryCodeModel(name:"Nicaragua",flag:"🇳🇮",code:"NI",dialCode:"+505"),
    CountryCodeModel(name:"Niger",flag:"🇳🇪",code:"NE",dialCode:"+227"),
    CountryCodeModel(name:"Nigeria",flag:"🇳🇬",code:"NG",dialCode:"+234"),
    CountryCodeModel(name:"Niue",flag:"🇳🇺",code:"NU",dialCode:"+683"),CountryCodeModel(name:"Norfolk Island",flag:"🇳🇫",code:"NF",dialCode:"+672"),CountryCodeModel(name:"Northern Mariana Islands",flag:"🇲🇵",code:"MP",dialCode:"+1670"),
    CountryCodeModel(name:"Norway",flag:"🇳🇴",code:"NO",dialCode:"+47"),
    CountryCodeModel(name:"Oman",flag:"🇴🇲",code:"OM",dialCode:"+968"),
    CountryCodeModel(name:"Pakistan",flag:"🇵🇰",code:"PK",dialCode:"+92"),
    CountryCodeModel(name:"Palau",flag:"🇵🇼",code:"PW",dialCode:"+680"),CountryCodeModel(name:"Palestinian Territory, Occupied",flag:"🇵🇸",code:"PS",dialCode:"+970"),
    CountryCodeModel(name:"Panama",flag:"🇵🇦",code:"PA",dialCode:"+507"),CountryCodeModel(name:"Papua New Guinea",flag:"🇵🇬",code:"PG",dialCode:"+675"),
    CountryCodeModel(name:"Paraguay",flag:"🇵🇾",code:"PY",dialCode:"+595"),
    CountryCodeModel(name:"Peru",flag:"🇵🇪",code:"PE",dialCode:"+51"),
    CountryCodeModel(name:"Philippines",flag:"🇵🇭",code:"PH",dialCode:"+63"),
    CountryCodeModel(name:"Pitcairn",flag:"🇵🇳",code:"PN",dialCode:"+64"),
    CountryCodeModel(name:"Poland",flag:"🇵🇱",code:"PL",dialCode:"+48"),
    CountryCodeModel(name:"Portugal",flag:"🇵🇹",code:"PT",dialCode:"+351"),CountryCodeModel(name:"Puerto Rico",flag:"🇵🇷",code:"PR",dialCode:"+1939"),
    CountryCodeModel(name:"Qatar",flag:"🇶🇦",code:"QA",dialCode:"+974"),
    CountryCodeModel(name:"Romania",flag:"🇷🇴",code:"RO",dialCode:"+40"),
    CountryCodeModel(name:"Russia",flag:"🇷🇺",code:"RU",dialCode:"+7"),
    CountryCodeModel(name:"Rwanda",flag:"🇷🇼",code:"RW",dialCode:"+250"),
    CountryCodeModel(name:"Reunion",flag:"🇷🇪",code:"RE",dialCode:"+262"),CountryCodeModel(name:"Saint Barthelemy",flag:"🇧🇱",code:"BL",dialCode:"+590"),CountryCodeModel(name:"Saint Helena, Ascension and Tristan Da Cunha",flag:"🇸🇭",code:"SH",dialCode:"+290"),CountryCodeModel(name:"Saint Kitts and Nevis",flag:"🇰🇳",code:"KN",dialCode:"+1869"),CountryCodeModel(name:"Saint Lucia",flag:"🇱🇨",code:"LC",dialCode:"+1758"),CountryCodeModel(name:"Saint Martin",flag:"🇲🇫",code:"MF",dialCode:"+590"),CountryCodeModel(name:"Saint Pierre and Miquelon",flag:"🇵🇲",code:"PM",dialCode:"+508"),CountryCodeModel(name:"Saint Vincent and the Grenadines",flag:"🇻🇨",code:"VC",dialCode:"+1784"),
    CountryCodeModel(name:"Samoa",flag:"🇼🇸",code:"WS",dialCode:"+685"),CountryCodeModel(name:"San Marino",flag:"🇸🇲",code:"SM",dialCode:"+378"),CountryCodeModel(name:"Sao Tome and Principe",flag:"🇸🇹",code:"ST",dialCode:"+239"),CountryCodeModel(name:"Saudi Arabia",flag:"🇸🇦",code:"SA",dialCode:"+966"),
    CountryCodeModel(name:"Senegal",flag:"🇸🇳",code:"SN",dialCode:"+221"),
    CountryCodeModel(name:"Serbia",flag:"🇷🇸",code:"RS",dialCode:"+381"),
    CountryCodeModel(name:"Seychelles",flag:"🇸🇨",code:"SC",dialCode:"+248"),CountryCodeModel(name:"Sierra Leone",flag:"🇸🇱",code:"SL",dialCode:"+232"),
    CountryCodeModel(name:"Singapore",flag:"🇸🇬",code:"SG",dialCode:"+65"),
    CountryCodeModel(name:"Slovakia",flag:"🇸🇰",code:"SK",dialCode:"+421"),
    CountryCodeModel(name:"Slovenia",flag:"🇸🇮",code:"SI",dialCode:"+386"),CountryCodeModel(name:"Solomon Islands",flag:"🇸🇧",code:"SB",dialCode:"+677"),
    CountryCodeModel(name:"Somalia",flag:"🇸🇴",code:"SO",dialCode:"+252"),CountryCodeModel(name:"South Africa",flag:"🇿🇦",code:"ZA",dialCode:"+27"),CountryCodeModel(name:"South Sudan",flag:"🇸🇸",code:"SS",dialCode:"+211"),CountryCodeModel(name:"South Georgia and the South Sandwich Islands",flag:"🇬🇸",code:"GS",dialCode:"+500"),
    CountryCodeModel(name:"Spain",flag:"🇪🇸",code:"ES",dialCode:"+34"),CountryCodeModel(name:"Sri Lanka",flag:"🇱🇰",code:"LK",dialCode:"+94"),CountryCodeModel(name:"Sudan",flag:"🇸🇩",code:"SD",dialCode:"+249"),
    CountryCodeModel(name:"Suriname",flag:"🇸🇷",code:"SR",dialCode:"+597"),CountryCodeModel(name:"Svalbard and Jan Mayen",flag:"🇸🇯",code:"SJ",dialCode:"+47"),
    CountryCodeModel(name:"Eswatini",flag:"🇸🇿",code:"SZ",dialCode:"+268"),
    CountryCodeModel(name:"Sweden",flag:"🇸🇪",code:"SE",dialCode:"+46"),
    CountryCodeModel(name:"Switzerland",flag:"🇨🇭",code:"CH",dialCode:"+41"),CountryCodeModel(name:"Syrian Arab Republic",flag:"🇸🇾",code:"SY",dialCode:"+963"),
    CountryCodeModel(name:"Taiwan",flag:"🇹🇼",code:"TW",dialCode:"+886"),
    CountryCodeModel(name:"Tajikistan",flag:"🇹🇯",code:"TJ",dialCode:"+992"),CountryCodeModel(name:"Tanzania, United Republic of Tanzania",flag:"🇹🇿",code:"TZ",dialCode:"+255"),
    CountryCodeModel(name:"Thailand",flag:"🇹🇭",code:"TH",dialCode:"+66"),
    CountryCodeModel(name:"Timor-Leste",flag:"🇹🇱",code:"TL",dialCode:"+670"),
    CountryCodeModel(name:"Togo",flag:"🇹🇬",code:"TG",dialCode:"+228"),
    CountryCodeModel(name:"Tokelau",flag:"🇹🇰",code:"TK",dialCode:"+690"),
    CountryCodeModel(name:"Tonga",flag:"🇹🇴",code:"TO",dialCode:"+676"),CountryCodeModel(name:"Trinidad and Tobago",flag:"🇹🇹",code:"TT",dialCode:"+1868"),
    CountryCodeModel(name:"Tunisia",flag:"🇹🇳",code:"TN",dialCode:"+216"),
    CountryCodeModel(name:"Turkey",flag:"🇹🇷",code:"TR",dialCode:"+90"),
    CountryCodeModel(name:"Turkmenistan",flag:"🇹🇲",code:"TM",dialCode:"+993"),CountryCodeModel(name:"Turks and Caicos Islands",flag:"🇹🇨",code:"TC",dialCode:"+1649"),
    CountryCodeModel(name:"Tuvalu",flag:"🇹🇻",code:"TV",dialCode:"+688"),
    CountryCodeModel(name:"Uganda",flag:"🇺🇬",code:"UG",dialCode:"+256"),
    CountryCodeModel(name:"Ukraine",flag:"🇺🇦",code:"UA",dialCode:"+380"),CountryCodeModel(name:"United Arab mirates",flag:"🇦🇪",code:"AE",dialCode:"+971"),CountryCodeModel(name:"United Kingdom",flag:"🇬🇧",code:"GB",dialCode:"+44"),CountryCodeModel(name:"United States",flag:"🇺🇸",code:"US",dialCode:"+1"),
    CountryCodeModel(name:"Uruguay",flag:"🇺🇾",code:"UY",dialCode:"+598"),
    CountryCodeModel(name:"Uzbekistan",flag:"🇺🇿",code:"UZ",dialCode:"+998"),
    CountryCodeModel(name:"Vanuatu",flag:"🇻🇺",code:"VU",dialCode:"+678"),CountryCodeModel(name:"Venezuela, Bolivarian Republic of Venezuela",flag:"🇻🇪",code:"VE",dialCode:"+58"),
    CountryCodeModel(name:"Vietnam",flag:"🇻🇳",code:"VN",dialCode:"+84"),CountryCodeModel(name:"Virgin Islands, British",flag:"🇻🇬",code:"VG",dialCode:"+1284"),CountryCodeModel(name:"Virgin Islands, U.S.",flag:"🇻🇮",code:"VI",dialCode:"+1340"),CountryCodeModel(name:"Wallis and Futuna",flag:"🇼🇫",code:"WF",dialCode:"+681"),
    CountryCodeModel(name:"Yemen",flag:"🇾🇪",code:"YE",dialCode:"+967"),
    CountryCodeModel(name:"Zambia",flag:"🇿🇲",code:"ZM",dialCode:"+260"),
    CountryCodeModel(name:"Zimbabwe",flag:"🇿🇼",code:"ZW",dialCode:"+263")]
